Cray-HPE/ims

- Dockerfile
- kubernetes/cray-ims/Chart.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- kubernetes/cray-ims/templates/post_upgrade_hook.yaml
- kubernetes/cray-ims/values.yaml
Add `alpine.image` settings to values.yaml in order to enable customization.
Change default alpine reference from `artifactory.algol60.net/docker.io/alpine:latest` to `alpine:latest`. Chart defaults should reference upstream locations instead of registry mirrors.
Supplements [CASMCMS-7618](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7618). Required to resolve [CASM-2670](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2670).
> Refactor alpine image references

- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
After testing it has been determined that the ims-utils container must run as the root user. This is due to several factors, but all relate to the fact that ims-utils must be able to read and modify the image root being created/customized. For instance, ims-utils must be able to add the root-ca certificate to the image root's /etc/cray/ca directory. Running as the nobody user, the ims-utils container does not have the permissions to do that. Additionally, ims-utils must be able to run the squashfs tool to archive the image root. Again, this cannot be done as the nobody user.
This ims-service PR changes the ims job configmaps to remove changing the ownership of various volumes. 
_List and …
> CASMCMS-7722 Roll back vol ownership changes

- api/openapi.yaml
- kubernetes/cray-ims/Chart.yaml
- kubernetes/cray-ims/values.yaml
- update_versions.conf
Zach Crisler noticed that the version tagging in the latest ims chart was messed up, Specifically, the version of ims-sshd had been used at the appVersion for ims itself. The underlying cause of this is because some of the version tags in update_versions.conf were ones that one might expect to find in the target files in other contexts. In this case, ims-sshd had a version tag of 3.4.5 specified. So when we tried to build that version of IMS, the update_versions script happily replaced that version with the version of ims-sshd.
This PR just replaces the possibly ambiguous version tags with ones that are extremely unlikely to show up otherwise. I followed the pattern of **0.0.0-label** that I saw used in a number of our other repos.
In theory I could put anything in this PR and it would …
> CASMCMS-7728: Use placeholder version strings that are unlikely to collide with actual version strings

- kubernetes/cray-ims/templates/configmap.yaml
- kubernetes/cray-ims/values.yaml
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
- tests/v2/test_v2_jobs.py
- tests/v3/test_v3_jobs.py
Update the default access pool for IMS jobs to be `customer-management` from `customer-access`. This change is in support of the work for the bifurcated-CAN and moves the IMS jobs to the management network. Essentially, this means that IMS Job pods are accessible to administrators only via the customer-management network. According to @johren-hpe this should not change any pod to pod communication, so it should not affect CFS communicating with IMS jobs. 
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ backwards compatible
* Resolves [CASMCMS-7703](https://connect.us.cray.com/jira/browse/CASMCMS-7703)
_List the environments in …
> CASMCMS-7703 Update jobs access pool to be customer-management

- CHANGELOG.md
- Dockerfile
- api/openapi.yaml
- kubernetes/cray-ims/templates/configmap.yaml
- requirements.txt
- src/server/models/jobs.py
- update_external_versions.conf
This picks up the changes in ims-utils, ims-sshd, ims-python-helper, and cray-ims-kiwi-ng-opensuse-x86_64-builder for updating the dev.cray.com addresses.  It also increases the default memory size for the ims jobs created since images are getting bigger and people are running into issues running out of space.
* Resolves [CASMCMS-7970](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7970)
* Resolves [CASMCMS-8015](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8015)
* `Fanta`
I upgraded to the new version via helm, then ran both an image customization job, as well as a recipe build job.  There were problems with the recipe build, but other people were seeing the same nexus access issues the build job was running into so it looks like ims is doing everything it is supposed to.
- …
> CSAMCMS-7970 - update dev.cray.com addresses.

- CHANGELOG.md
- config/gunicorn.py
- kubernetes/cray-ims/templates/configmap.yaml
- kubernetes/cray-ims/values.yaml
- src/server/app.py
There were timeouts configured for connections and read times, but the overall application was timing out when an s3 file operation was taking over 30 seconds.  This caused the gunicorn application that is running inside the ims pod to restart, dropping the operation that was in progress.
This change adds the timeout configuration value to the gunicorn application and makes it configurable through the helm charts and ims-config k8s configmap.
There is also a change to the readiness/liveness probes to increase their timing as well.  The way they were configured, when an operation took long enough, the liveness probe would fail and the container would be restarted mid-operation.  There should be a better solution for this put into place at some point. Currently the http server is …
> CASMTRIAGE-4091 - make gunicorn worker timeout configurable.

- CHANGELOG.md
- kubernetes/cray-ims/values.yaml
The ims service is single-threaded, so while it is performing an operation it is not able to respond to liveness/readiness queries. When the image sizes get to 5-13Gb, sometimes the liveness probe will kill the ims container in the middle of an image copy.  This increases the timings to allow longer operations until we can get a better solution in place.
* Resolves [CASMTRIAGE-4288](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4288)
* Resolves [CASMTRIAGE-4268](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4268)
* Resolves [CASMTRIAGE-4091](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4091)
* `Mug`
* `Loki`
The settings were changes manually in the deployment on Loki and with these changes can successfully work with 13Gb gpu images.
- Were the …
> CASMTRIAGE-4288 - handle operations on larger images without k8s timing out.

- CHANGELOG.md
- Kata.README.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-packer-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
Changes the default runtime of ims jobs to be that of kata-qemu. 
Changes the medium for emptyDir from memory to blank. This is due to a limitation of kata utilizing volume subpaths.
See. https://github.com/kata-containers/runtime/issues/1341
Mug 
IMS jobs utilizing kata-qemu runtimeclass to successfully build and customize IMS images.
_Are there known issues with these changes? Any other special considerations?_
Wont work if kata is not installed on the system.
> kata runtime class, remove memory medium from volume spec

- CHANGELOG.md
- kubernetes/cray-ims/values.yaml
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
Update the k8s api interface used for the istio service. This will bring us up to date with the most recent version and keep us from having depreciation problems as k8s is upgraded.
* Resolves [CASMCMS-8347](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8347)
* `Surtur`
I upgraded the image being used on surtur and verified that jobs started correctly and the istio connections are created successfully.
This is a low risk change as it upgrades the interface version but there are no …
> CASMCMS-8347 - update istio api interface version to v1beta1.

- CHANGELOG.md
- api/openapi.yaml
I discovered when working in the Cray CLI repo that the IMS API spec file there was out of date. In the process of correcting that, I discovered that the IMS spec file here in the repo has some incorrect information in it -- that is, the actual behavior of the IMS service does not match what is currently in the spec file.
While updating the spec file to correct the above, I also did some small linting of the formatting and language, mainly to try and make it more consistent.
There are no functional changes from this PR -- it is purely intended to make the API spec match the API behavior.
* [Corresponding PR in the Cray CLI repo](https://github.com/Cray-HPE/craycli/pull/66) to update the IMS spec file there as well
I ran the API spec validation tool documented in the IMS repo README file …
> CASMCMS-8382: Correct openapi spec to match actual API behavior; minor linting of spec

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- update_external_versions.conf
For image customization jobs to support arm64, it needs the arch setting pushed to the sshd container so the emulation can be set up.
* Resolves [CASMCMS-8365](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8365)
* `Mug`
Manually updated the customize job template, then successfully ran the arm64 customization jobs. The entire service will be installed on a fresh system shortly for a true verification that everything is set up in the code correctly.
Low risk - just adding a new templated …
> CASMCMS-8567 - support arm64 image customization.

- CHANGELOG.md
- kubernetes/cray-ims/values.yaml
Update arm64 build default runtime to kata
[CASMCMS-8566](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8566)
Mug
> update default arm64 runtime to kata, update changelog

- .gitignore
- CHANGELOG.md
- api/openapi.yaml
- src/server/helper.py
- src/server/models/jobs.py
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
- tests/v2/test_v2_jobs.py
- tests/v3/test_v3_jobs.py
Currently the craycli commands for IMS default to using `vmlinuz` as the `kernel_file_name` in the jobs API. This change allows IMS to rename the `kernel_file_name` relative to the architecture of the image or recipe.
IMS jobs create will now accept `Image | vmlinuz | None` depending if ARM or x86.
Backwards compatiable
* Resolves [CASMCMS-8624](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8624)
This PR should be accompanied with a following craycli update to the `ims` module.
* `Mug`
> CASMCMS-8624: job creation kernel name default is x86 specific

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
Needed to change volume configuration from emptyDir to a PVC. Kata containers using emptyDir was giving a "none" filesystem type which caused unsquashfs to fail due to being unable to handle file attributes on a "none" type. 
* Resolves [issue id](issue link) [CASMCMS-8362](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8362)
Tested the PVC configuration on Mugenstein.
> hotfix for customize, PVC volume

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-packer-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
Rolled back PVC changes. Utilize kata annotations to directly configure virtiofs behaviour to enable xattr.
* Resolves [CASMCMS-8362](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8362)
Tested on Mug
After enabling annotations in qemu hypervisor file, edited ims creation/customize configmaps to include virtiofs arguments.
No risks forseen for this.
> rollback PVC changes, utilize annotations for virtiofs args xattr

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-packer-job-template.yaml
Roll back the annotations from the create CM templates so the kata filesystem annotations are only being applied to the customize job.
* Resolves [CASMCMS-8362](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8362)
* `Mug`
Tested the recipe builds with the new settings in the CM.
Medium risk change as we are not sure of the downstream implications, but it shouldn't be any worse off than we were before.
> CASMCMS-8362 - rollback annotation from create jobs.

- CHANGELOG.md
- src/server/models/jobs.py
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
There are 2 issues wrapped together in this hotfix:
CASMCMS-8686 - fix jobs record scheme change on helm update.
CASMCMS-8687 - fix global require-dkms setting usage.
Both were found when doing more extensive testing of the csm-1.5 release version of IMS.
* Resolves [CASMCMS-8686](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8686)
* Resolves [CASMCMS-8687](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8687)
* `Mug`
I did a clean install of the csm-1.4 version of IMS on Mug, then did helm upgrade/downgrade testing to insure the schema of the jobs records is correctly updated, and the global require-dkms flag is being used as expected.
- Were continuous integration tests run? If not, …
> CASMCMS-8686/8687 - fixes for csm-1.5 release

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
The build arch env variable was not being set in all containers for the IMS jobs kicked off. That meant that it was defaulting to 'x86_64' and in the case of customizing an 'aarch64' image, when complete it was getting incorrectly uploaded and labeled as an 'x86_64' image.
This adds the 'BUILD_ARCH' env variable to the job templates for the containers that was missing that variable. This will get set to the correct value when IMS templates the job and now flows through with the correct value.
* Resolves [CASMCMS-8707](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8707)
* `Mug`
I installed the new IMS helm chart on Mug, then ran jobs to insure the correct values are getting picked up and set.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation …
> CASMCMS-8707 - push arch env vars to all containers in IMS jobs.

- CHANGELOG.md
- kubernetes/cray-ims/templates/configmap.yaml
- kubernetes/cray-ims/templates/cray-ims-rbac.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-packer-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- kubernetes/cray-ims/templates/post_upgrade_hook.yaml
- src/server/app.py
- src/server/models/jobs.py
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
- tests/v2/test_v2_jobs.py
- tests/v3/test_v3_jobs.py
There is a limited amount of ephemeral storage on the k8s cluster. We were seeing cases where IMS jobs were failing due to insufficient resources. In order to resolve this, I switched the primary image and recipe mounts in the IMS jobs to use PVC's for volume mounts instead of the ephemeral storage they were using.
* Resolves [CASMCMS-8801](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8801)
* Change will also be needed in ims-utils and ims-kiwi-builder repos.
* `Mug`
I did a helm install/upgrade/downgrade. I ran all the dkms and non/dkms recipe build and customization permutations. They all performed as expected. There is a change to the job data record (to keep track of the PVC created for the job) and I did upgrade/downgrade testing.
- Were the install/upgrade-based validation …
> CASMCMS-8801 - switch jobs to use PVC's for image mounts.

- CHANGELOG.md
- kubernetes/cray-ims/templates/configmap.yaml
When PVC's were introduced for image storage we decreased the memory requests and limit sizes to make scheduling jobs easier. With some larger jobs, the new default was not sufficient, so this bumps it back up a bit.
* Resolves [CASMCMS-8828](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8828)
* `Slice`
Manual change of the setting resulted in successful job completion.
Very low risk - just increasing resource allocations.
> CASMCMS-8828 - increase default mem size for jobs.

- CHANGELOG.md
- api/openapi.yaml
- constraints.txt
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- requirements.txt
- src/server/__init__.py
- src/server/app.py
- src/server/models/jobs.py
- src/server/models/remote_build_nodes.py
- src/server/v2/resources/jobs.py
- src/server/v3/__init__.py
- src/server/v3/resources/jobs.py
- src/server/v3/resources/remote_build_nodes.py
- tests/v2/test_v2_jobs.py
- tests/v3/ims_fixtures.py
- tests/v3/test_v3_jobs.py
- tests/v3/test_v3_public_keys.py
- tests/v3/test_v3_recipes.py
- tests/v3/test_v3_remote_build_nodes.py
Update IMS to handle adding/removing/querying remote-build-nodes and add them to the job templating.
* Resolves [CASMCMS-8795](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8795)
* `Mug`
Installed new helm chart and verified the new API works and kicks off builds with the remote-build-node option if a node is defined and matches the job criteria.
Medium size risk as we are adding a new API and it is impacting the job creation.
> CASMCMS-8795 - add remote build node objects.

- CHANGELOG.md
- kubernetes/cray-ims/templates/configmap.yaml
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
- update_external_versions.conf
Integrate the changes from ims-sshd to fix sftp use on customize jobs, and increase the default memory requirements / limits to handle bigger images work without changing IMS defaults.
* Resolves [CASMTRIAGE-6368](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6368)
* Resolves [CASMTRIAGE-6292](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6292)
* `Mug`
I did a clean helm install of the new IMS service and tested the ssh/sftp access on jobs, and verified the new updated memory settings are present.
- Were new tests (or test issues/Jiras) created for …
> CASMTRIAGE-6368/6292 - include ims-sshd fix for sftp, increase default mem requirements/limits.

- CHANGELOG.md
- kubernetes/cray-ims/templates/configmap.yaml
Needed to increase the size of PVC for IMS due to resource constraints when building large images.
https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6426
drax
Increased the PVC size which unblocked the resource constraint.
No
> CASMTRIAGE-6426 update default IMS pvc size

- CHANGELOG.md
- Dockerfile
- api/openapi.yaml
- constraints.txt
- kubernetes/cray-ims/templates/cray-ims-rbac.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- requirements.txt
- src/server/__init__.py
- src/server/app.py
- src/server/models/jobs.py
- src/server/models/remote_build_nodes.py
- src/server/v2/resources/jobs.py
- src/server/v3/__init__.py
- src/server/v3/resources/jobs.py
- src/server/v3/resources/remote_build_nodes.py
- src/server/vault.py
- tests/v2/test_v2_jobs.py
- tests/v3/ims_fixtures.py
- tests/v3/test_v3_jobs.py
- tests/v3/test_v3_public_keys.py
- tests/v3/test_v3_recipes.py
- tests/v3/test_v3_remote_build_nodes.py
- update_external_versions.conf
The ssh keys for IMS to use for communicating with the remote build nodes are stored in vault. This takes them from vault and makes them available for the jobs to use them.
* Resolves [CASMCMS-8823](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8823)
* `Mug, Baldar`
Installed via helm, then used to run remote jobs on both x86 and aarch64 remote build nodes.
Medium risk - in line with the rest of the feature.
> CASMCMS-8823 - generate ssh keys from vault.

- CHANGELOG.md
- src/server/vault.py
There was a case where vault was not accessible and the ims service was in CLBO due to unhandled exceptions in valut.py. This is code that is just trying to access ssh keys for remote build nodes. This is not used by all deployments, so should not take down the entire service.
This code does more error checking / handling to not crash if vault is not working correctly.
* Resolves [CASMCMS-8925](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8925)
* `Baldar`
I created an image with a simulated vault failure (vault was fixed on the machine by the time I was testing) and verified that the condition was handled cleanly.
- Was upgrade …
> CASMCMS-8925 - better error handling for vault access.

- CHANGELOG.md
- lib/shasta_s3_creds.py
This addresses the same problem (in the same module) that Ryan addressed in cray-aee with [CASMTRIAGE-6799](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6799). The PR content is identical:
https://github.com/Cray-HPE/ansible-execution-environment/pull/64
This addresses an incompatibility with the updated Kubernetes module version.
I verified that this module fails on CSM 1.6 systems inside the IMS pod, but that it works with this fix.
> CASMCMS-8950: Fix Kubernetes client initialization in shasta_s3_creds module

- CHANGELOG.md
- constraints.txt
IMS rebuilds in `master` branch started failing because the unit tests began to fail. Investigation revealed that the version of `pytest` was not pinned, and the tests started failing when it went from 8.1.1 to 8.2.0. I have verified that pinning it to 8.1.1 avoids the failures.
> CASMCMS-9001: Pin pytest version to prevent unit test failures

- CHANGELOG.md
- constraints.txt
(cherry picked from commit 572918cc97c14d3721b0cb46059faf9e0a391a25)
> CASMCMS-9001: Pin pytest to prevent unit test failures

- CHANGELOG.md
- update_external_versions.conf
DST has published a new signing key for zypper repos that we include in the kiwi-builder image. This changes updates the version that IMS includes to get that fix incorporated.
* Resolves [CASMCMS-8976](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8976)
Tested under https://github.com/Cray-HPE/ims-kiwi-ng-opensuse-x86_64-builder/pull/73
> CASMCMS-8976 - include updated kiwi-builder version to get new DST signing key.

- CHANGELOG.md
- api/openapi.yaml
This corrects the openapi spec file to make it symmetric with what the CLI will be using as tested.
* Resolves [CASMCMS-8833](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8833)
* `wasp`
Installed new IMS service image and new craycli and tested out the features by hand.
> Make openapi changes symmetric with CLI

- CHANGELOG.md
- api/openapi.yaml
- src/server/models/jobs.py
- src/server/models/remote_build_nodes.py
- src/server/v3/__init__.py
- src/server/v3/resources/remote_build_nodes.py
- tests/v3/test_v3_remote_build_nodes.py
Add a new endpoint to the IMS service to report the status of all remote build nodes. This will help users determine if jobs will run remotely or if there is something misconfigured with the remote build nodes.
* Resolves [CASMCMS-8979](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8979)
* Change will also be needed in `craycli` and `docs-csm` repos.
* `Mug`
I installed the new IMS service and updated cray cli onto mug, then tried different configurations of remote build nodes to insure that the status was being reported correctly for each remote node in each case. …
> CASMCMS-8979 - add remote build node status endpoint.

- CHANGELOG.md
- src/server/models/jobs.py
- src/server/v3/resources/remote_build_nodes.py
- src/server/vault.py
There are a few cases where on initialization of the IMS service, the ssh key is not able to be fetched from vault. That would result in the remote build nodes being inaccessible until the service was restarted.
With this change, each time the remote nodes would be accessed (either to find one for creating a job, or to get remote build node status information) it checks if the key is present. If it isn't present, it attempts to fetch it again. 
* Resolves [CASMCMS-8977](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8977)
* `Mug`
I installed the new container on Mug and manually deleted the key file inside the container to simulate the key not getting fetched on initialization. After that I executed remote node operations that require the key and verified that the key was correctly …
> CASMCMS-8977 - refetch ssh key if not present.

- CHANGELOG.md
- src/server/models/jobs.py
- src/server/models/remote_build_nodes.py
Clean up the default value of number of jobs for the remote build node status object. Using 10000 was weird - made it -1 for unknown.
* Resolves [CASMCMS-8979](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8979)
* `Mug`
Updated to the new image and tested with valid and invalid remote build nodes. Ran multiple jobs, make sure the number of current jobs was correct.
Very low risk.
> CASMCMS-8979 - update status unknown jobs.

- CHANGELOG.md
- kubernetes/cray-ims/values.yaml
- src/server/models/jobs.py
- src/server/models/recipes.py
- src/server/v2/resources/jobs.py
- src/server/v3/models/recipes.py
- src/server/v3/resources/jobs.py
There was a request by cos to have the require-dkms default to 'true' instead of 'false' like it originally released. This changes the defaults and had to modify the logic a little bit to get it right for integrating with the 'require_dkms' flag in the recipe records.
* Resolves [CASMINST-6602](https://jira-pro.it.hpe.com:8443/browse/CASMINST-6602)
* `Mug`
I deployed the new helm chart to ensure the correct default value is applied to the ims-config settings. I then tested each combination of global and per record settings to make sure the correct use of dkms was determined in each scenario.
- Was …
> CASMINST-6602 - enable dkms by default.

- CHANGELOG.md
- kubernetes/cray-ims/templates/configmap.yaml
- src/server/models/jobs.py
[CASMTRIAGE-7252](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7252) was opened because a CFS image customization session failed because the default IMS image size was too small. In an ideal world, this wouldn't happen because:
* CFS would try to get an idea of how big the image is, and specify an appropriate `build_env_size` to the IMS job that it creates.
or
* If no `build_env_size` was specified, IMS would try to determine a reasonable one based on the other parameters.
However, both of those are obviously more complicated things to implement. So this PR takes the safer route of just increasing our default IMS image size to a value that does not hit the problem in question.
> CASMTRIAGE-7252: Increase DEFAULT_IMS_IMAGE_SIZE from 30 to 60

- CHANGELOG.md
- kubernetes/cray-ims/Chart.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- kubernetes/cray-ims/values.yaml
- src/server/models/jobs.py
This wraps 3 changes into one PR:
CASMTRIAGE-7327 - Fix picking up the correct defaults from the ims-config configmap.
CASMTRIAGE-7274 - Fix the cpu limits for the containers to not overdrive the kata VM.
CASMCMS-9147 - Stop using alpine:latest - switch to the CSM rebuilt version.
* Resolves [CASMTRIAGE-7327](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7327)
* Resolves [CASMTRIAGE-7274](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7274)
* Resolves [CASMCMS-9147](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9147)
* `Mug, Tyr, Fanta, Gamora`
I have installed the package via helm on Mug to insure the upgrade/downgrade worked correctly and tested changing the ims-config settings and verified they flowed through to the job settings as they should. This also verified the alpine …
> CASMTRIAGE-7327 - fix reading default values from ims-config.

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
The anti-affinity section was set up incorrectly. This resolved that issue.
* Resolves [CASMTRIAGE-7401](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7401)
* Change will also be needed in `node_images` repo
* `starlord`
I installed the new version via helm and insured the anti-affinity is working correctly to spread out both build and customize jobs across all available worker nodes.
- Was downgrade tested? If not, why? Y
This is low risk.
> CASMTRIAGE-7401 - fix job pod anti-affinity.

- CHANGELOG.md
- src/server/v3/resources/images.py
When an image was deleted and a 'deleted image' object was created, it wasn't recording the arch of the image. This was making it always default to 'x86_64', so 'aarch64' images were being recorded 'x86_64' images.
This just pushes the correct value through the delete / undelete process.
* Resolves [CASMCMS-9166](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-9166)
* `Mug`
I used Helm to install the test version on Mug and insured that delete/undelete now retains the correct 'arch' value throughout.
- Was downgrade tested? If not, why? Y
- Were new tests (or test issues/Jiras) created for this …
> CASMCMS-9166 - fix image delete/undelete preserving arch.

- CHANGELOG.md
- constraints.txt
- kubernetes/cray-ims/values.yaml
- src/server/app.py
- src/server/config.py
- src/server/helper.py
- tests/v3/test_v3_deleted_images.py
- tests/v3/test_v3_deleted_recipes.py
- tests/v3/test_v3_images.py
- tests/v3/test_v3_recipes.py
The 'soft delete' of IMS objects used the S3 'copy_from' command. This command does the copy in a single atomic operation but is limited to artifacts less than 5Gb in size. When the rootfs files got bigger than 5Gb, the copy into the 'deleted objects' location would fail, leaving them behind. Then when the 'deleted image' was deleted, these artifacts were not removed from S3.
The fix is to use the S3 'copy' command which uses a multi-part copy if the object is too larger for the single operation copy. There is an issue with S3/boto3 where the multi-part copy fails if the artifact is owned by a different user than the 'IMS' user. I had to put code in to handle the copy differently if the artifact is owned by 'STS' which is the case if 'cray artifacts create' is used to load the artifact …
> CASMCMS-9201 - Fix orphaned artifacts in S3.

- CHANGELOG.md
- Dockerfile
- update_external_versions.conf
Alpine 3.15 no longer receives security patches.
I tested this on wasp and verifies it works.
> CASMCMS-9282: Bump Alpine version from 3.15 to 3.21

- CHANGELOG.md
- src/server/v3/resources/recipes.py
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9363:IMS - deleted recipe always gets assigned arch=x86_64
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta
Tested …
> CASMCMS-9363:IMS - deleted recipe always gets assigned arch=x86_64

- CHANGELOG.md
- api/openapi.yaml
This PR corrects several errors in the IMS API spec:
1. The API spec lists `ImageRecord` as both the schema you should send to create a new record, and also the schema for the format of image descriptions you get back from IMS. However, with the addition of the metadata field, this is no longer accurate. So this PR creates a new `ImageCreateRecord` schema (similar to the `ImagePatchRecord` schema), which is is the schema used when creating a new image. This schema actually matches the current `ImageRecord` schema.
2. The `ImageRecord` and `DeletedImageRecord` schemas in the IMS API spec are inaccurate in their definitions of the metadata field. 
They both specify that field as follows:
```yaml
metadata:
description: User supplied annotations about an image
type: object
properties:
key: …
```
> CASMCMS-9386: API spec: Correct schemas for metadata fields in ImageRecord and DeletedImageRecord

- CHANGELOG.md
- src/server/v2/resources/images.py
- src/server/v3/resources/images.py
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9389: Soft delete/restore Persisting the metadata of an image
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta …
> CASMCMS-9389: Soft delete/restore Persisting the metadata of an image

- CHANGELOG.md
- src/server/v3/resources/recipes.py
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9396: Persist require_dkms during soft delete/restore
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta
Tested on mug …
> CASMCMS-9396: Persist require_dkms during soft delete/restore

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-rbac.yaml
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMCMS-9408:Conditionalize podsecuritypolicies references in cray-ims
* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `<development system>`
* Virtual Shasta …
> CASMCMS-9408:Conditionalize podsecuritypolicies references in cray-ims

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-rbac.yaml
CASMCMS-9408: Conditionalize podsecuritypolicies references in cray-ims
cray-ims chart (3.23.0) has references to podsecuritypolicies that needs to be conditionalized for deployment on CSM 1.7.
> CASMCMS-9408: Conditionalize podsecuritypolicies references in cray-ims

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-rbac.yaml
CASMCMS-9452: Cleanup of leftover Cluster/RoleBindings under CMS
Deployed the service on mug
> CASMCMS-9452:Cleanup of leftover Cluster/RoleBindings under CMS

- CHANGELOG.md
- update_external_versions.conf
CASMCMS-9455: Updated ims-utils version to 2.18
This IMS utils version has fix for following JIRA
- CASMCMS-9455: Building image from recipe Job stuck at waiting_for_repos status
- CASMCMS-9364: Confirm exposed SSH private key impact in ims-python-helper
- CASMCMS-8022: It also contains python module updates for `ims-python-helper` and -ims-utils`
> CASMCMS-9455: Updated ims-utils version to 2.18

- CHANGELOG.md
CASMCMS-8022: Updated `ims-utils` version to `2.18` and `kiwi-ng` version to `1.10`
This `ims-utils` and `kiwi-ng` version has fix for following JIRA
CASMCMS-9455: Building image from recipe Job stuck at waiting_for_repos status
CASMCMS-9364: Confirm exposed SSH private key impact in ims-python-helper
CASMCMS-8022: It also contains python module updates for ims-python-helper and -ims-utils`
> develop->master CASMCMS-8022: Updated `ims-utils` version to `2.18` and `kiwi-ng` version to `1.10`

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- update_external_versions.conf
CASMCMS-9510: Added LOG_LEVEL ENV in build image and customize image configmap
The change adds the flexibility to the users to change logging level during `build image` and `customize image`. 
This was tested on `mug`. Following tests were run for `build image` and `customize image`
> `LOG_LEVEL` ENV set to `INFO` 
> `LOG_LEVEL` ENV set to `WARNING`
> `LOG_LEVEL` ENV set to `DEBUG`
> Remove `LOG_LEVEL` ENV variable  from build image` and `customize image` configmap.
> CASMCMS-9510: Added LOG_LEVEL ENV in build image and customize image configmap

- CHANGELOG.md
- kubernetes/cray-ims/templates/cray-ims-v2-image-create-kiwi-ng-job-template.yaml
- kubernetes/cray-ims/templates/cray-ims-v2-image-customize-job-template.yaml
- src/server/v2/resources/jobs.py
- src/server/v3/resources/jobs.py
- update_external_versions.conf
Make changes to the remote build process to minimize extra work copying and squashing/unsquashing the image. This pushes more work to happen on the remote node so that once the image file is transferred back to the job pod it no longer needs further modification.
This also makes a small change to delete PVC resources when the job is complete. These volumes can be large and once the pod has finished they are not really useful. The other resources are kept for debugging purposes.
This requires changes in:
ims
ims-utils
ims-sshd
ims-kiwi-ng-opensuse-x86_64-builder
* Resolves [CASMCMS-8904](https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8904)
* `Mug`, and `Odin`
Installed the changes on the system and built complete images (from uss recipe, including shs, cos, gpu, sma, etc products) both …
> CASMCMS-8904 - remote build optimizations.
